### ISSUE TITLE
Command to create a new Fyord boilerplate project

### ISSUE THREAD

**Issue by justinhhorner** [Fyord/fyord-cli#3]
We want developers to be able to quickly and easily create a new Fyord app using the CLI.

This new command should create a new Fyord app based on the [boilerplate](https://github.com/Fyord/fyord-boilerplate) in the current working directory.

**Comment by bayes343** [comment]
Linked a pull request.

Still need to override names in a few places (package, index, etc.) and add tests, but I got the cloning of the boilerplate project, removing its .git and initing a new one with an initial commit working.
